### ISSUE TITLE
image-type doesn't want an ArrayBuffer

### ISSUE THREAD

**Issue by freaktechnik** [dy/image-decode#1]
It appears `image-type` doesn't want an ArrayBuffer, but a `Uint8Array` or a `Buffer`. However https://github.com/dy/image-decode/blob/master/index.js#L10 turns `Uint8Arrays` into an `ArrayBuffer`, leading to an error being thrown.

Edit: or more precisely, `file-type` which is used by `image-type` doesn't like the `ArrayBuffer`, though `image-type` seems to advertise itself as a lib for `Uint8Array`s and `Buffer`s.

**Comment by dy** [comment]
Fixed! Thanks!
