### ISSUE TITLE
File not supported as binary data container

### ISSUE THREAD

**Issue by Tassfighter** [dy/image-decode#2]
When I call decode with a js **file** the result is _null_

image-decode uses _to-array-buffer_ internally and tries to convert to array buffer.
But _to-array-buffer_ does not support js **file** [see](https://www.npmjs.com/package/to-array-buffer
)

For the moment I will use npm _blob-util_ to convert to array buffer.

**Comment by dy** [comment]
Could you pls elaborate what do you mean by _file_? That'd be great if you provided source code.

**Comment by Tassfighter** [comment]
I mean a blob file [see](https://developer.mozilla.org/de/docs/Web/API/File)

The _image-decode_  docu say:

> buffer can be any binary data container:
> ArrayBuffer
> Buffer
> Uint8Array
> **File**
> Blob
> base64 string

The _to-array-buffer_ docu says:

> Turn any binary data container into an ArrayBuffer in sync way. Detected containers:
> 
> Buffer
> TypedArray
> ArrayBufferView
> ArrayBuffer
> data-uri string
> base64 string
> plain string
> Array
> Array of Arrays
> Number (creates new ArrayBuffer of the defined length in bytes)
> etc.

In _image-decode_ the first call of decode goes to_to-array-buffer_ and that returns _null_.

My workaround is to call first:
`blobUtil.blobToArrayBuffer(image);`

**Comment by dy** [comment]
@Tassfighter got you. Yes, that's confusing message, removed it.
`image-decode` intends to be synchronous, and since there's no way to decode _Blob_/_File_ synchronously in main thread, using the `blob-util` or similar is the right choice.

Thanks for the report.
